accounts:
  - name: dl1
    coins: ["100000ogn", "1000000ogns"]
  - name: dl2
    coins: ["100000ogn", "1000000ogns"]
validator:
  name: dl1
  staked: "1000000ogns"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: dl2
  coins: ["100ogn", "1000ogns"]
  port: 4500