accounts:
  - name: dl1
    coins: ["100000token", "1000000stake"]
  - name: dl2
    coins: ["100000token", "1000000stake"]
validator:
  name: dl1
  staked: "1000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: dl2
  coins: ["100token", "1000stake"]
  port: 4500